version: '3.7'

services:
  goggles-db:
    image: mariadb:10.3.25
    container_name: goggles-db
    ports:
      - '33060:3306'
    env_file:
      - .env
    restart: always
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
        volume:
          nocopy: true

  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: steveoro/goggles-api:staging-0.1.2
    depends_on:
      - goggles-db
    container_name: goggles-api.staging
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env

volumes:
  db_data:
  gem_cache:
  node_modules:
