version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: steveoro/goggles-api:test-0.1.1
    depends_on:
      - goggles-db
    container_name: goggles-api
    restart: "no"
    ports:
      - '8080:8080'
    env_file:
      - .env

  goggles-db:
    image: mariadb:10.3.25
    container_name: goggles-db
    ports:
      - '33060:3306'
    env_file:
      - .env
    restart: "no"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
        volume:
          nocopy: true

volumes:
  db_data:
  gem_cache:
  node_modules:
