# Allow full customization when building a new Docker image:
default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV.fetch("DATABASE_USER") { 'root' } %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: goggles_development

test:
  <<: *default
  database: goggles_test

production:
  <<: *default
  database: goggles
